# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160804_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='external_id',
        ),
    ]
