# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_on',
        ),
    ]
